spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;DATABASE_TO_UPPER=false;INIT=create schema if not exists public;
    driverClassName: org.h2.Driver
flyway:
  locations:
    - classpath:db/migration
    - filesystem:testdata
