spring:
  datasource:
    url: jdbc:mysql://db:3306/ex_db
    driverClassName: com.mysql.jdbc.Driver
    username: ex_user
    password: ex_pass
flyway:
  locations:
    - classpath:db/migration
    - filesystem:/var/local/testdata
