version: '2'
services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: adminpass
      MYSQL_DATABASE: ex_db
      MYSQL_USER: ex_user
      MYSQL_PASSWORD: ex_pass
    volumes:
      - ./data:/var/lib/mysql
  ap:
    image: tomcat:8.5-jre8
    environment:
      TZ: Asia/Tokyo
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ../app/build/libs/example-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/example.war
    ports:
      - 8080:8080
    links:
      - db
