version: '2'
services:
  db:
    image: mysql
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --general_log=1
      --general_log_file=/var/log/mysql/query.log
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: adminpass
      MYSQL_DATABASE: ex_db
      MYSQL_USER: ex_user
      MYSQL_PASSWORD: ex_pass
    volumes:
      - ./data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
  ap:
    image: tomcat:8.5-jre8
    environment:
      TZ: Asia/Tokyo
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
      spring.datasource.driverClassName: com.mysql.jdbc.Driver
      spring.datasource.url: jdbc:mysql://db:3306/ex_db
      spring.datasource.username: ex_user
      spring.datasource.password: ex_pass
      flyway.locations: classpath:db/migration,filesystem:/var/local/testdata
    volumes:
      - ../app/build/libs/example-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/example.war
      - ./server.xml:/usr/local/tomcat/conf/server.xml
      - ./logs/tomcat/:/usr/local/tomcat/logs/
      - ./testdata/:/var/local/testdata/
    command: catalina.sh jpda run
    ports:
      - 8080:8080
      - 8000:8000
    links:
      - db
  tcpdump:
    build: ./tcpdump
    command: tcpdump -s0 -X -G 1 -w /var/log/dump/tcpdump_%Y%m%d_%H%M%S.cap port 8080
    network_mode: "service:ap"
    environment:
      TZ: Asia/Tokyo
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./logs/dump/:/var/log/dump/
